image: node:18-alpine

cache:
  paths:
    - client/node_modules/
    - client/.next/cache/

pages:
  before_script:
    - cd client
    - npm install
  script:
    - npm run build
    - cd ..
    - mkdir -p public
    - cp -r client/.next public/.next   # copy the build output
    - cp client/package.json public/    # needed for SSR
  after_script:
    - echo "Cleanup done"
  artifacts:
    paths:
      - public
  only:
    - main
