image: node:18-alpine

cache:
  paths:
    - client/node_modules/
    - client/.next/cache/

pages:
  before_script:
    # Install packages
    - cd client
    - npm install
  script:
    # Build application and move content to public folder
    - npm run build
    - cd ..
    - mkdir public

  artifacts:
    paths:
      - public
  only:
    - main

