image: node:18

stages:
  - install
  - run

install_dependencies:
  stage: install
  script:
    - cd client
    - npm ci
    - cd ../backend
    - pip install -r requirements.txt

run_servers:
  stage: run
  script:
    - cd backend
    - uvicorn main:app --host 0.0.0.0 --port 8000 &
    - cd ../client
    - npm run start
    - sleep 10
    - curl http://localhost:8000
    - curl http://localhost:3000
