
image: python:3.11

services:
  - docker:dind

variables:
  NODE_ENV: development

stages:
  - install
  - run

install_dependencies:
  stage: install
  script:
    - apt update && apt install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt install -y nodejs
    - node -v && npm -v
    - cd client && npm ci
    - cd ../backend && pip install -r requirements.txt

run_servers:
  stage: run
  script:
    - cd backend
    - uvicorn main:app --host 0.0.0.0 --port 8000 &
    - cd ../client
    - npm run start &
    - sleep 10  # Give time for servers to start
    - curl http://localhost:8000  # Test backend
    - curl http://localhost:3000  # Test frontend
