image: node:18-alpine   # default image for all jobs

stages:
  - test
  - build

# TODO: placeholder until we fix genome
stub-test:
  stage: test
  script:
    - echo "No tests enabled"

## Python tests
#pytest:
#  stage: test
#  image: python:3.12
#  cache:
#    key: pip-cache
#    paths:
#      - .cache/pip
#  before_script:
#    - python -m pip install --upgrade pip
#    # Install both runtime and test dependencies, but not dev
#    - pip install --cache-dir .cache/pip -r requirements.txt -r requirements-test.txt
#  script:
#    - pytest --maxfail=1 --disable-warnings -q

# Build and deploy Next.js client
pages:
  cache:
    paths:
      - client/node_modules/
      - client/.next/cache/

  before_script:
    # Install packages
    - cd client
    - npm ci

  script:
    # Build application and move content to public folder
    - npm run build
    - cd ..
    - mkdir public
    # move the produced out directory into public
    - mv client/out/* public

  after_script:
    # Cleanup
    - rm -rf client/out

  artifacts:
    paths:
      - public

  only:
    - main