version: "3.9"

services:
  genome-bootstrap:
    image: python:3.11-slim
    environment:
      GENOME_FETCH_METHOD: ${GENOME_FETCH_METHOD:-curl}
      HG38_TARGET_DIR: /genome-cache
      ASODESIGNER_HG38_URL: ${ASODESIGNER_HG38_URL:-https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz}
    volumes:
      - genome-cache:/genome-cache
      - .:/workspace
    entrypoint: ["/bin/bash", "/workspace/scripts/bootstrap_hg38.sh"]

  backend:
    image: python:3.11-slim
    depends_on:
      genome-bootstrap:
        condition: service_completed_successfully
    working_dir: /workspace
    environment:
      PYTHONUNBUFFERED: "1"
      ASODESIGNER_HG38_PATH: /genome-cache/hg38.fa
    volumes:
      - .:/workspace
      - genome-cache:/genome-cache:ro
    command: >-
      bash -c "pip install --no-cache-dir -r backend/requirements.txt && \
      uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

volumes:
  genome-cache:
