image: node:18-alpine

cache:
  paths:
    - client/node_modules/
    - client/.next/cache/

pages:
  before_script:
    # Install packages
    - cd client
    - npm ci
  script:
    # Build application and move content to public folder
    - npm run build
    - cd ..
    - mkdir public
    # move the produced out directory into public
    - mv backend/uploads/* public
  after_script:
    # Cleanup
    - rm -rf backend/uploads/
  artifacts:
    paths:
      - public
  only:
    - main
